name:                x1
version:             0.0.1
homepage:            https://github.com/luc-tielen/x1-lang#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2019 Luc Tielen
category:            Web
extra-source-files:
- README.md
- CONTRIBUTING.md
- CHANGELOG.md
- LICENSE

dependencies:
  - base >= 4.11.0 && < 5

default-extensions:
  - LambdaCase

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -optP-Wno-nonportable-include-path

library:
  source-dirs:        lib

executables:
  x1:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - x1

tests:
  x1-test:
    main:             test.hs
    source-dirs:      tests
    dependencies:
      - tasty >= 1.1.0 && < 2
      - tasty-hspec >= 1.1.5 && < 2
      - tasty-discover >= 4.2.1 && < 5
      - x1

