version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci

    steps:
      - checkout
      - run:
          name: Linting
          command: nix-shell --option sandbox false --run "make lint"
          no_output_timeout: 60m
      - run:
          name: Unit tests
          command: nix-shell --option sandbox false --run "make configure tests focus_check"
          no_output_timeout: 60m
      - run:
          name: Build executable
          command: nix-shell --option sandbox false --run "cabal build exe:besra"
          no_output_timeout: 60m
